### ISSUE TITLE
SlaveException: column name 'GAIA_RA' not found (case insensitive)

### ISSUE THREAD

**Issue by moustakas** [desihub/desitarget#336]
@geordie666 I was trying to select a sample of ELGs from the COSMOS truth field and `select_targets` crashed.  Perhaps we shouldn't *require* the Gaia tags in the code?  

I also just noticed that there's an optional `gaiadir` input which assumes a NERSC infrastructure (i.e., not laptop-friendly).  If this directory isn't set does the code still proceed (again, under the theory that I don't---momentarily!---care about stars).

Here's a code snippet and the full traceback---

```python
from desitarget.cuts import select_targets
targ = select_targets('/global/projecta/projectdirs/desi/target/analysis/truth/dr7.0/matched/decals-dr7.0-cosmos-acs-match.fits')

---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
~/repos/desihub/desitarget/py/desitarget/internal/sharedmem.py in get(self, Q)
    376             try:
--> 377                 return Q.get(timeout=1)
    378             except queue.Empty:

/usr/local/anaconda3/envs/desi/lib/python3.6/multiprocessing/queues.py in get(self, block, timeout)
    104                     if not self._poll(timeout):
--> 105                         raise Empty
    106                 elif not self._poll():

Empty: 

During handling of the above exception, another exception occurred:

StopProcessGroup                          Traceback (most recent call last)
~/repos/desihub/desitarget/py/desitarget/internal/sharedmem.py in map(self, func, sequence, reduce, star)
    673                 try:
--> 674                     capsule = pg.get(R)
    675                 except queue.Empty:

~/repos/desihub/desitarget/py/desitarget/internal/sharedmem.py in get(self, Q)
    379                 if not self.is_alive():
--> 380                     raise StopProcessGroup
    381                 else:

StopProcessGroup: StopProcessGroup

During handling of the above exception, another exception occurred:

SlaveException                            Traceback (most recent call last)
<ipython-input-9-f1b5451e3b7c> in <module>()
----> 1 targ = select_targets('decals-dr7.0-cosmos-acs-match.fits')

~/repos/desihub/desitarget/py/desitarget/cuts.py in select_targets(infiles, numproc, qso_selection, match_to_gaia, sandbox, FoMthresh, Method, gaiadir)
   2241                 targets = pool.map(_select_sandbox_targets_file, infiles, reduce=_update_status)
   2242             else:
-> 2243                 targets = pool.map(_select_targets_file, infiles, reduce=_update_status)
   2244     else:
   2245         targets = list()

~/repos/desihub/desitarget/py/desitarget/internal/sharedmem.py in map(self, func, sequence, reduce, star)
    676                     continue
    677                 except StopProcessGroup:
--> 678                     raise pg.get_exception()
    679                 capsule = capsule[0], realreduce(capsule[1])
    680                 heapq.heappush(L, capsule)

SlaveException: column name 'GAIA_RA' not found (case insensitive)
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/desi/lib/python3.6/site-packages/fitsio/fitslib.py", line 2622, in _extract_colnum
    colnum = self._colnames_lower.index(colstr.lower())
ValueError: 'gaia_ra' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ioannis/repos/desihub/desitarget/py/desitarget/internal/sharedmem.py", line 265, in _slaveMain
    self.main(self, *self.args)
  File "/Users/ioannis/repos/desihub/desitarget/py/desitarget/internal/sharedmem.py", line 563, in _main
    r = realfunc(work)
  File "/Users/ioannis/repos/desihub/desitarget/py/desitarget/internal/sharedmem.py", line 629, in realfunc
    else: return func(i)
  File "/Users/ioannis/repos/desihub/desitarget/py/desitarget/cuts.py", line 2206, in _select_targets_file
    objects = io.read_tractor(filename)
  File "/Users/ioannis/repos/desihub/desitarget/py/desitarget/io.py", line 304, in read_tractor
    data = fx[1].read(columns=readcolumns)
  File "/usr/local/anaconda3/envs/desi/lib/python3.6/site-packages/fitsio/fitslib.py", line 1805, in read
    data = self.read_columns(columns, **keys)
  File "/usr/local/anaconda3/envs/desi/lib/python3.6/site-packages/fitsio/fitslib.py", line 1987, in read_columns
    colnums = self._extract_colnums(columns)
  File "/usr/local/anaconda3/envs/desi/lib/python3.6/site-packages/fitsio/fitslib.py", line 2599, in _extract_colnums
    colnums[i] = self._extract_colnum(columns[i])
  File "/usr/local/anaconda3/envs/desi/lib/python3.6/site-packages/fitsio/fitslib.py", line 2624, in _extract_colnum
    raise ValueError(mess)
ValueError: column name 'GAIA_RA' not found (case insensitive)

```

**Comment by geordie666** [comment]
@moustakas: This has been fixed as part of the DR7 targeting update, in a branch I haven't yet pushed. I should push that branch tomorrow or the next day, though (once I complete all of the targeting updates).

**Comment by geordie666** [comment]
Oh, and as part of that work-in-progress branch, you'll be able to request that only `ELGs` (or only any individual target class) be selected.

**Comment by geordie666** [comment]
Oh, also, does this work for you:

`targ = select_targets('/global/projecta/projectdirs/desi/target/analysis/truth/dr7.0/matched/decals-dr7.0-cosmos-acs-match.fits', match_to_gaia=False)`

?

That was my intended option for people who definitely didn't want to match to the Gaia directory.

**Comment by moustakas** [comment]
Setting `match_to_gaia=False` still crashes with the same error.  I'll stand by for the DR7 code updates, thanks.

**Comment by moustakas** [comment]
With the master branch of `desitarget` here's the new traceback:

```python

ERROR:cuts.py:684:isSTD_gaia: GAIA_DUPLICATED_SOURCE (dupsource) should be boolean!

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-73be92750353> in <module>()
----> 1 targ = select_targets('decals-dr7.0-cosmos-acs-match.fits', numproc=1)

~/repos/desihub/desitarget/py/desitarget/cuts.py in select_targets(infiles, numproc, qso_selection, gaiamatch, sandbox, FoMthresh, Method, tcnames, gaiadir)
   2511         else:
   2512             for x in infiles:
-> 2513                 targets.append(_update_status(_select_targets_file(x)))
   2514 
   2515     targets = np.concatenate(targets)

~/repos/desihub/desitarget/py/desitarget/cuts.py in _select_targets_file(filename)
   2466         objects = io.read_tractor(filename)
   2467         desi_target, bgs_target, mws_target = apply_cuts(objects,qso_selection,
-> 2468                                                          gaiamatch,tcnames,gaiadir)
   2469 
   2470         return _finalize_targets(objects, desi_target, bgs_target, mws_target)

~/repos/desihub/desitarget/py/desitarget/cuts.py in apply_cuts(objects, qso_selection, gaiamatch, tcnames, gaiadir)
   2154             gaia=gaia, astrometricexcessnoise=gaiaaen, paramssolved=gaiaparamssolved,
   2155             pmra=pmra, pmdec=pmdec, parallax=parallax, dupsource=gaiadupsource,
-> 2156             gaiagmag=gaiagmag, gaiabmag=gaiabmag, gaiarmag=gaiarmag, bright=False)
   2157         std_bright = isSTD(primary=primary, zflux=zflux, rflux=rflux, gflux=gflux,
   2158             gfracflux=gfracflux, rfracflux=rfracflux, zfracflux=zfracflux,

~/repos/desihub/desitarget/py/desitarget/cuts.py in isSTD(gflux, rflux, zflux, primary, gfracflux, rfracflux, zfracflux, gfracmasked, rfracmasked, zfracmasked, gnobs, rnobs, znobs, gfluxivar, rfluxivar, zfluxivar, objtype, gaia, astrometricexcessnoise, paramssolved, pmra, pmdec, parallax, dupsource, gaiagmag, gaiabmag, gaiarmag, bright)
    756                       pmra=pmra, pmdec=pmdec, parallax=parallax,
    757                       dupsource=dupsource, paramssolved=paramssolved,
--> 758                       gaiagmag=gaiagmag, gaiabmag=gaiabmag, gaiarmag=gaiarmag)
    759 
    760     #ADM apply type=PSF cut

~/repos/desihub/desitarget/py/desitarget/cuts.py in isSTD_gaia(primary, gaia, astrometricexcessnoise, pmra, pmdec, parallax, dupsource, paramssolved, gaiagmag, gaiabmag, gaiarmag)
    683     if not (dupsource.dtype.type == np.bool_):
    684         log.error('GAIA_DUPLICATED_SOURCE (dupsource) should be boolean!')
--> 685         raise IOError
    686 
    687     #ADM a unique Gaia source

OSError: 

```

**Comment by geordie666** [comment]
The error message is telling you what the problem is `GAIA_DUPLICATED_SOURCE` should be boolean, not an integer, otherwise the logic cuts will fail in misleading ways.

`GAIA_DUPLICATED_SOURCE` is boolean in the 7.1 sweeps. Are you still running the 7.0 sweeps?

**Comment by moustakas** [comment]
Yes, that's it then. The truth catalogs were matched against the 7.0
sweeps. I'll ask Rongpu to regenerate them.

**Comment by moustakas** [comment]
Fixed in #338 and after using the truth catalogs matched against the 7.1 sweeps.
